package com.prashant.pib.video_synthesis_service.service;

import com.prashant.pib.video_synthesis_service.dto.GeneratedVideoResponse;
import com.prashant.pib.video_synthesis_service.dto.PublishVideoRequest;
import java.util.List;

public interface GeneratedVideoService {

    GeneratedVideoResponse generateVideo(Long pressReleaseId, String username);

    // NEW overload (preferred by controller)
    GeneratedVideoResponse generateVideo(Long pressReleaseId, String username, String language, String scriptOverride);

    GeneratedVideoResponse publishVideo(Long videoId, PublishVideoRequest request, String username);

    // CHANGE signature to support language + hints
    String improviseContent(Long pressReleaseId, String username, String language, String styleHints);

    GeneratedVideoResponse getVideoStatusByJobId(String jobId);

    // --- ARCHITECTURAL FIX: Adding essential video retrieval methods ---

    /**
     * Retrieves a single video by its primary key ID, ensuring the user is authorized.
     * @param videoId The ID of the video to fetch.
     * @param username The username of the person requesting the video, for authorization.
     * @return The video details.
     */
    GeneratedVideoResponse getVideoById(Long videoId, String username);

    /**
     * Retrieves a list of all videos generated by the currently authenticated user.
     * @param username The username of the current user.
     * @return A list of the user's videos.
     */
    List<GeneratedVideoResponse> getVideosForCurrentUser(String username);

    /**
     * Retrieves a list of every video in the system. FOR ADMINS ONLY.
     * @return A list of all videos.
     */
    List<GeneratedVideoResponse> getAllVideos();

    // ✅ NEW
    List<GeneratedVideoResponse> getPublishedVideos();
}